# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Cacti"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Simple and elegante theme for gardeners. Forked from hexo theme cactus created by @probberechts."
homepage = "https://github.com/matiargs/hugo-theme-cacti"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Matias Micheltorena"
  homepage = "https://www.matiargs.com"

# If porting an existing theme
[original]
  author = "Pieter Robberechts"
  homepage = "https://github.com/probberechts"
  repo = "https://github.com/probberechts/hexo-theme-cactus"
